version: '3.7'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: url_minifier_api
      POSTGRES_PASSWORD: sample
      POSTGRES_DB: url_minifier_api
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - data-volume:/var/lib/postgresql/data
    command: [ "postgres", "-c", "log_statement=all", "-c", "timezone=UTC" ]
  tracing:
    image: jaegertracing/all-in-one:latest
    environment:
      - "COLLECTOR_ZIPKIN_HTTP_PORT=9411"
    ports:
      - "5775:5775/udp"
      - "16686:16686"
      - "6831:6831/udp"
      - "6832:6832/udp"
volumes:
  data-volume: